[package]
name = "wasmtime-bindings-macro"
version = "0.1.0"
authors = ["Yury Delendik <ydelendik@mozilla.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.2"
syn = "1.0.5"
proc-macro2 = "1.0.3"

[features]
default = ["syn/full", "syn/extra-traits"]
